// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backExamen.Config;

#nullable disable

namespace backExamen.Migrations
{
    [DbContext(typeof(FlotaDBContext))]
    [Migration("20230329155756_porFavor")]
    partial class porFavor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backExamen.Models.TipoVehiculoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NombreTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tipos_vehiculos");
                });

            modelBuilder.Entity("backExamen.Models.VehiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int?>("TipoVehiculoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoVehiculoid");

                    b.ToTable("vehiculos");
                });

            modelBuilder.Entity("backExamen.Models.VehiculoModel", b =>
                {
                    b.HasOne("backExamen.Models.TipoVehiculoModel", "TipoVehiculo")
                        .WithMany("VehiculosDeEsteTipo")
                        .HasForeignKey("TipoVehiculoid");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("backExamen.Models.TipoVehiculoModel", b =>
                {
                    b.Navigation("VehiculosDeEsteTipo");
                });
#pragma warning restore 612, 618
        }
    }
}
